import fbprocess as fb
import json


def main():
    """Process the name and id from posts.

    Reads in a JSON file of Facebook posts generated by fbexpages.py
    e.g. CitizensAdvice.json

    Replaces names with first name longer then 2 characters
    using:
    fb.extract_first_name

    Replaces ids with hashed ids using:
    fb.md_5_hash

    then saves into a new JSON file e.g. CitizensAdviceClean.json
    """

    posts = fb.read_json('CitizensAdvice.json')

    for post in posts:
        for r in post['reactions']['data']:
            r['id'] = fb.extract_value('id', r, fb.md_5_hash)
            r['name']= fb.extract_value('name', r, fb.extract_first_name)
        for c in post['comments']['data']:
            f = c['from']
            f['id'] = fb.extract_value('id', f, fb.md_5_hash)
            f['name']= fb.extract_value('name', f, fb.extract_first_name)

    clean_posts = fb.write_json(posts, 'CitizensAdviceClean.json')

    return True


if __name__ == '__main__':
    main()
